# Monitors
monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:60,x:-1920,y:0
monitorrule=make:ASUSTek COMPUTER INC,model:PA248QV,width:1920,height:1200,refresh:59.950,x:0,y:0
monitorrule=make:XXX,model:AAA,width:1366,height:76ZZrefresh:59.790,x:1920,y:0

# Assign applications to tags
windowrule=tags:4,appid:vesktop
windowrule=tags:6,appid:steam
windowrule=tags:7,appid:gimp
windowrule=tags:7,appid:Inkscape

# Float QuickShell windows
windowrule=isfloating:1,appid:^dev\.noctalia$
windowrule=isfloating:1,appid:^steam$

# Scratchpads
windowrule=isnamedscratchpad:1,width:900,height:700,appid:sp-btop
windowrule=isnamedscratchpad:1,width:900,height:700,appid:sp-cmus

# Terminal swallowing
windowrule=isterm:1,appid:foot
windowrule=isterm:1,appid:yazi
