#!/usr/bin/env bash
# file preview handler for lf

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"
CACHE_DIR="/tmp/lf"

if [ ! -d "$CACHE_DIR" ]; then
	mkdir -p /tmp/lf
fi

image() {
	if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
	else
		exiftool "$6"
	fi
}

ifub() {
	[ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1
}

case "$(file --dereference --brief --mime-type -- "$1")" in
	*/tgz|*/tar*) tar tzf "$1";;
	*/tar.bz2|*/tbz2) tar tjf "$1";;
	*/tar.txz|*/txz) xz --list "$1";;
	*/tar) tar tf "$1";;
	application/*zip|*/jar|*/war|*/ear|*/oxt) unzip -l "$1";;
	*/rar) unrar l "$1";;
	*/7z) 7z l "$1";;
	*/[1-8]) man "$1" | col -b ;;
	*/o) nm "$1" | less ;;
	application/x-bittorrent) transmission-show "$1";;
	image/avif) CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
		[ ! -f "$CACHE" ] && convert "$1" "$CACHE.jpg"
		image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1" ;;
	image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
	text/html) bat --terminal-width "$(($4-2))" -p -f "$1" ;;
	text/troff) man ./ "$1" | col -b ;;
	text/* | */xml | application/json) bat --terminal-width "$(($4-2))" -f -p "$1" ;;
	audio/* | application/octet-stream) exiftool "$1" || exit 1 ;;
	video/* )
		CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
		[ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
		image "$CACHE" "$2" "$3" "$4" "$5" "$1"
		;;
	*/pdf)
		CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
		[ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
		;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
