#!/bin/sh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# pacman
alias \
	ch="checkupdates ; pikaur -Qua 2>/dev/null" \
	pacman="pikaur" \
	up="pikaur -Syu" \
	pco="pacman -Qtdq | sudo pacman -Rns -" \
	pacunlock="sudo rm /var/lib/pacman/db.lck" \
	paclog="cat /var/log/pacman.log" \
	mirrors="sudo reflector --latest 20 --fastest 20 --number 10 --sort rate --verbose --save /etc/pacman.d/mirrorlist"

# dotfiles
alias \
	conf="git --git-dir=$HOME/repos/dotfiles.git --work-tree=$HOME" \
	confs="conf status -s" \
	confd="conf diff" \
	confc="conf commit" \
	confp="conf push" \

# verbosity and options
alias \
	df="df -h" \
	free="free -mt" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	ip="ip -color=auto" \
	mkd="mkdir -pv" \
	rcp="rsync -avP"
	# wget="wget --hsts-file=$XDG_CACHE_HOME/.wget-hist"

# abbreviations
alias \
	_="sudo" \
	yta="yt-dlp -x --audio-format mp3 --audio-quality 0" \
	ytw="yt-dlp --output '%(title).200B%(title.201B&…|)s.%(ext)s'" \
	nb="newsboat" \
	trem="transmission-remote" \
	trex="transmission-remote --exit" \
	iv="imgview" \
	cuetag="cuetag.sh" \
	mpva="mpv --audio-display=no --no-video" \
	o="xdg-open" \
	z="zathura"

# hipster coreutil replacements
alias \
	ls="exa --color=always --group-directories-first --icons" \
	ll="ls -l" \
	la="ls -al" \
	lh="ls -d .*" \
	tree="ls --tree" \
	cat="bat -p" \
	less="bat"

# non-hipster replacements
alias \
	lf="lfpv"
	# vim="nvim"

# git
alias \
	gst="git status" \
	ga="git add" \
	gfa="git ls-files -m -o --exclude-standard | fzf -m --print0 | xargs -0 git add" \
	gc="git commit" \
	gco="git checkout" \
	gl="git pull" \
	gp="git push" \
	gd="git diff" \
	gb="git branch" \
	gba="git branch -a" \
	gdl="git branch -d"

# shortcuts
alias \
	md="cd $HOME/documents/notes && ls" \
	bme="$EDITOR $HOME/documents/bmks/urls" \
	bmd="bmks del" \
	cf="cd ~/.config && ls" \
	lb="cd ~/.local/bin && ls" \
	lsr="cd ~/.local/src && ls" \
	rp="cd ~/repos && ls"

# plugins
alias \
	zshplugs="find \"$ZDOTDIR/plugins\" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
