#!/bin/zsh

# pacman
alias \
	ch="checkupdates; yay -Quq" \
	paclog="less /var/log/pacman.log" \
	mirrors="sudo reflector --latest 20 --fastest 20 --number 10 --sort rate --verbose --save /etc/pacman.d/mirrorlist"

# verbosity and options
alias \
	df="df -h" \
	free="free -mt" \
	cp="cp -iv" \
	mv="mv -iv" \
	ip="ip -color=auto"

# abbreviations
alias \
	yta="yt-dlp -x --audio-format mp3 --audio-quality 0" \
	ytw="yt-dlp --output '%(title).200B%(title.201B&…|)s.%(ext)s'" \
	trem="transmission-remote" \
	trex="transmission-remote --exit" \
	v="imgview" \
	cuetag="cuetag.sh" \
	mpa="mpv --audio-display=no --no-video" \
	o="xdg-open" \
	z="zathura"

# hipster coreutil replacements
alias \
	ls="eza --color=always --group-directories-first --icons=always --hyperlink" \
	ll="ls -l" \
	la="ls -al" \
	lh="ls -d .*" \
	tree="ls --tree" \
	# less="/usr/share/nvim/runtime/scripts/less.sh"
    #cat="bat -p" \
	#less="bat"

# git
alias \
	gst="git status" \
	ga="git add" \
	gfa="git ls-files -m -o --exclude-standard | fzf -m --print0 | xargs -0 git add" \
	gc="git commit" \
	gco="git checkout" \
	gl="git pull" \
	gp="git push" \
	gd="git diff" \
	gb="git branch" \
	gba="git branch -a" \
	gdl="git branch -d"
