#!/bin/zsh
# .zprofile
# gatoneg.ro

# Host name
export HOSTNAME=$(cat /etc/hostname)

# Host-dependent variables
if [ ${HOSTNAME} = "foxes" ]; then
	export VDPAU_DRIVER=radeonsi
	export LIBVA_DRIVER_NAME=radeonsi
fi

if [ ${HOSTNAME} = "lucille" ]; then
	export MPV_PROFILE="--profile=720p"
fi

# XDG Base Directories
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

# Terminal
export TERM="xterm-kitty"
export TERMINAL="kitty"

# Editor
export EDITOR="vim"
export VISUAL="vim"

# Manpager
export MANPAGER="nvim +Man!"

# Browser
export BROWSER="firefox"

# File manager
export FILEMANAGER="yazi"

# zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Export zsh path
typeset -U path
path=(~/.local/bin ~/.local/bin/statusbar $path)

# ssh-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# Xorg
export XAUTHORITY=$XDG_CACHE_HOME/X11/Xauthority
export XINITRC=$XDG_CONFIG_HOME/X11/xinitrc

# XDG compliance for various programmes
export CARGO_HOME=$XDG_DATA_HOME/cargo
export GNUPGHOME=$XDG_CONFIG_HOME/gnupg
export GOPATH=$XDG_DATA_HOME/go
export LESSHISTFILE=$XDG_CACHE_HOME/lesshst
export NPM_CONFIG_PREFIX=$XDG_DATA_HOME/node/node_modules
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export _JAVA_OPTIONS=-Djavafx.cachedir=$XDG_CACHE_HOME/openjfx
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java 
export WGETRC=$XDG_CONFIG_HOME/wgetrc
export PYTHONSTARTUP="${XDG_CONFIG_HOME:-$HOME/.config}/python/pythonstartup.py"
export SUDO_ASKPASS="$HOME/.local/bin/rofi-pass"

# Start Xorg session
# [ -z "$DISPLAY" ] && [ $XDG_VTNR -eq 1 ] && startx $XINITRC

# Start niri Wayland session
[ -z "$DISPLAY" ] && [ $XDG_VTNR -eq 1 ] && niri-session
