#!/bin/sh
# gatoneg.ro

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
fi

[ -r $XDG_CONFIG_HOME/X11/xprofile ] && . $XDG_CONFIG_HOME/X11/xprofile
[ -r $XDG_CONFIG_HOME/X11/Xresources ] && xrdb -merge $XDG_CONFIG_HOME/X11/Xresources
[ -r $XDG_CONFIG_HOME/X11/Xmodmap ] && xmodmap $XDG_CONFIG_HOME/X11/Xmodmap

if [ ${HOSTNAME} = "psyche" ]; then
	[ -r $XDG_CONFIG_HOME/X11/HiDPI ] && xrdb -merge $XDG_CONFIG_HOME/X11/HiDPI
	# workaround for muted sound on boot
	pamixer -t && pamixer -t
fi

# autostart
# lxsession &
picom -b &
numlockx on &
sxhkd &
dunst &
jamesdsp --tray &
redshift -l $(cat $XDG_CONFIG_HOME/latlong) &
setwall $HOME/pictures/wallpapers &
xss-lock -- slock &
ffplay -v 0 -nodisp -autoexit $XDG_CONFIG_HOME/startup.ogg &
emacs --daemon &

# dwm
exec dwm
