#!/bin/bash

updates=$(checkupdates)

if [ -z "$updates" ]
then 
	notify-send -t 5000 -u normal "No updates available" \
	"All packages are up to date." \
	-i ~/.icons/arch-logo-240px.png
else
	notify-send -t 5000 -u normal "System updates available" \
	"The following packages can be updated:\n$updates" \
	-i ~/.icons/arch-logo-240px.png
fi
