# Theme is just tokyonight with transparency
inherits = "tokyonight"

"ui.background" = { bg = "", fg = "fg" }
"ui.cursorline.primary" = { bg = "" }
"ui.help" = { bg = "", fg = "fg" }
"ui.text" = { bg = "", fg = "fg" }
"ui.text.focus" = { bg = "bg-focus" }
"ui.text.info" = { bg = "", fg = "fg" }
"ui.virtual.ruler" = { bg = "fg-gutter" }
"ui.virtual.inlay-hint" = {  bg = "", fg = "teal" }
