#!/bin/sh
case "$1" in
	"C-w") while read file; do xwallpaper --zoom "$file" & done ;;
	"C-d") while read file; do trash-put "$file" & done ;;
	"C-b") while read file; do \
		if [ -e "${file%jpg}"epub ]; then \
			xdg-open "${file%jpg}"epub & \
		elif [ -e "${file%jpg}"pdf ]; then \
			xdg-open "${file%jpg}"pdf & \
		fi
		killall nsxiv & \
		done ;;
esac
