[mgr]
prepend_keymap = [
	{ on = [ "g", "d" ], run = "cd ~/downloads",              desc = "Go to the downloads directory" },
	{ on = "S",          run = "shell --block --confirm zsh", desc = "Start a new shell" },
	{ on = [ "s", "f" ], run = "search fd",                   desc = "Search files (fd)" },
	{ on = [ "s", "r" ], run = "search rg",                   desc = "Search contents (ripgrep)" },
	{ on = "j", run = "arrow 1" },
	{ on = "k", run = "arrow -1" },
]
