# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[ ](bold red)[](bold cyan)'
error_symbol = '[ ](bold red)'
vimcmd_symbol = "[](bold green)"

[directory]
format='[\[](green)[$path]($style)[\]](green)[$read_only]($read_only_style) '
style = 'white'
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "../"
read_only = "  "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
