# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ ](bold red)[](bold cyan)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[directory]
format='[\[](green)[$path]($style)[\]](green)[$read_only]($read_only_style) '
style = 'white'
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
