# helix text editor
# gatoneg.ro

theme = "gatonegro_neon"

[editor]
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
Z = { Q = ":q!", Z = ":wq" }
D = [ "goto_line_start", "select_mode", "goto_line_end_newline", "delete_selection", "normal_mode" ]
C-w = ":w"